/*
 * XgeneCloud
 * Create APIs at the speed of your thoughts
 *
 * OpenAPI spec version: 1.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.18
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.XgeneCloud) {
      root.XgeneCloud = {};
    }
    root.XgeneCloud.CofDictEntryI18n = factory(root.XgeneCloud.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';

  /**
   * The CofDictEntryI18n model module.
   * @module model/CofDictEntryI18n
   * @version 1.0.0
   */

  /**
   * Constructs a new <code>CofDictEntryI18n</code>.
   * @alias module:model/CofDictEntryI18n
   * @class
   */
  var exports = function() {
  };

  /**
   * Constructs a <code>CofDictEntryI18n</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/CofDictEntryI18n} obj Optional instance to populate.
   * @return {module:model/CofDictEntryI18n} The populated <code>CofDictEntryI18n</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();
      if (data.hasOwnProperty('ID'))
        obj.ID = ApiClient.convertToType(data['ID'], 'String');
      if (data.hasOwnProperty('DICT_ENTRY_ID'))
        obj.DICT_ENTRY_ID = ApiClient.convertToType(data['DICT_ENTRY_ID'], 'String');
      if (data.hasOwnProperty('LOCALE'))
        obj.LOCALE = ApiClient.convertToType(data['LOCALE'], 'String');
      if (data.hasOwnProperty('DICT_ENTRY_NAME'))
        obj.DICT_ENTRY_NAME = ApiClient.convertToType(data['DICT_ENTRY_NAME'], 'String');
      if (data.hasOwnProperty('IS_FIXED'))
        obj.IS_FIXED = ApiClient.convertToType(data['IS_FIXED'], 'Number');
    }
    return obj;
  }

  /**
   * @member {String} ID
   */
  exports.prototype.ID = undefined;

  /**
   * @member {String} DICT_ENTRY_ID
   */
  exports.prototype.DICT_ENTRY_ID = undefined;

  /**
   * @member {String} LOCALE
   */
  exports.prototype.LOCALE = undefined;

  /**
   * @member {String} DICT_ENTRY_NAME
   */
  exports.prototype.DICT_ENTRY_NAME = undefined;

  /**
   * @member {Number} IS_FIXED
   */
  exports.prototype.IS_FIXED = undefined;


  return exports;

}));
