/*
 * XgeneCloud
 * Create APIs at the speed of your thoughts
 *
 * OpenAPI spec version: 1.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.18
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.XgeneCloud) {
      root.XgeneCloud = {};
    }
    root.XgeneCloud.CofEmp = factory(root.XgeneCloud.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';

  /**
   * The CofEmp model module.
   * @module model/CofEmp
   * @version 1.0.0
   */

  /**
   * Constructs a new <code>CofEmp</code>.
   * @alias module:model/CofEmp
   * @class
   */
  var exports = function() {
  };

  /**
   * Constructs a <code>CofEmp</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/CofEmp} obj Optional instance to populate.
   * @return {module:model/CofEmp} The populated <code>CofEmp</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();
      if (data.hasOwnProperty('ID'))
        obj.ID = ApiClient.convertToType(data['ID'], 'String');
      if (data.hasOwnProperty('CODE'))
        obj.CODE = ApiClient.convertToType(data['CODE'], 'String');
      if (data.hasOwnProperty('NAME'))
        obj.NAME = ApiClient.convertToType(data['NAME'], 'String');
      if (data.hasOwnProperty('REALNAME'))
        obj.REALNAME = ApiClient.convertToType(data['REALNAME'], 'String');
      if (data.hasOwnProperty('GENDER'))
        obj.GENDER = ApiClient.convertToType(data['GENDER'], 'String');
      if (data.hasOwnProperty('BIRTHDAY'))
        obj.BIRTHDAY = ApiClient.convertToType(data['BIRTHDAY'], 'String');
      if (data.hasOwnProperty('STATUS'))
        obj.STATUS = ApiClient.convertToType(data['STATUS'], 'String');
      if (data.hasOwnProperty('CARD_TYPE'))
        obj.CARD_TYPE = ApiClient.convertToType(data['CARD_TYPE'], 'String');
      if (data.hasOwnProperty('CARD_NO'))
        obj.CARD_NO = ApiClient.convertToType(data['CARD_NO'], 'String');
      if (data.hasOwnProperty('IN_DATE'))
        obj.IN_DATE = ApiClient.convertToType(data['IN_DATE'], 'String');
      if (data.hasOwnProperty('OUT_DATE'))
        obj.OUT_DATE = ApiClient.convertToType(data['OUT_DATE'], 'String');
      if (data.hasOwnProperty('FAN_NO'))
        obj.FAN_NO = ApiClient.convertToType(data['FAN_NO'], 'String');
      if (data.hasOwnProperty('MOBILE_NO'))
        obj.MOBILE_NO = ApiClient.convertToType(data['MOBILE_NO'], 'String');
      if (data.hasOwnProperty('DESCRIPTION'))
        obj.DESCRIPTION = ApiClient.convertToType(data['DESCRIPTION'], 'String');
      if (data.hasOwnProperty('CREATE_TIME'))
        obj.CREATE_TIME = ApiClient.convertToType(data['CREATE_TIME'], 'String');
      if (data.hasOwnProperty('UPDATE_TIME'))
        obj.UPDATE_TIME = ApiClient.convertToType(data['UPDATE_TIME'], 'String');
      if (data.hasOwnProperty('TENANT_ID'))
        obj.TENANT_ID = ApiClient.convertToType(data['TENANT_ID'], 'String');
      if (data.hasOwnProperty('PARTY'))
        obj.PARTY = ApiClient.convertToType(data['PARTY'], 'String');
      if (data.hasOwnProperty('DEGREE'))
        obj.DEGREE = ApiClient.convertToType(data['DEGREE'], 'String');
      if (data.hasOwnProperty('REMARK'))
        obj.REMARK = ApiClient.convertToType(data['REMARK'], 'String');
      if (data.hasOwnProperty('O_TEL'))
        obj.O_TEL = ApiClient.convertToType(data['O_TEL'], 'String');
      if (data.hasOwnProperty('O_ADDRESS'))
        obj.O_ADDRESS = ApiClient.convertToType(data['O_ADDRESS'], 'String');
      if (data.hasOwnProperty('O_EMAIL'))
        obj.O_EMAIL = ApiClient.convertToType(data['O_EMAIL'], 'String');
      if (data.hasOwnProperty('H_TEL'))
        obj.H_TEL = ApiClient.convertToType(data['H_TEL'], 'String');
      if (data.hasOwnProperty('H_ADDRESS'))
        obj.H_ADDRESS = ApiClient.convertToType(data['H_ADDRESS'], 'String');
      if (data.hasOwnProperty('H_ZIPCODE'))
        obj.H_ZIPCODE = ApiClient.convertToType(data['H_ZIPCODE'], 'String');
      if (data.hasOwnProperty('P_EMAIL'))
        obj.P_EMAIL = ApiClient.convertToType(data['P_EMAIL'], 'String');
      if (data.hasOwnProperty('QQ'))
        obj.QQ = ApiClient.convertToType(data['QQ'], 'String');
      if (data.hasOwnProperty('WEIBO'))
        obj.WEIBO = ApiClient.convertToType(data['WEIBO'], 'String');
      if (data.hasOwnProperty('WECHAT'))
        obj.WECHAT = ApiClient.convertToType(data['WECHAT'], 'String');
      if (data.hasOwnProperty('IS_FIXED'))
        obj.IS_FIXED = ApiClient.convertToType(data['IS_FIXED'], 'Number');
    }
    return obj;
  }

  /**
   * @member {String} ID
   */
  exports.prototype.ID = undefined;

  /**
   * @member {String} CODE
   */
  exports.prototype.CODE = undefined;

  /**
   * @member {String} NAME
   */
  exports.prototype.NAME = undefined;

  /**
   * @member {String} REALNAME
   */
  exports.prototype.REALNAME = undefined;

  /**
   * @member {String} GENDER
   */
  exports.prototype.GENDER = undefined;

  /**
   * @member {String} BIRTHDAY
   */
  exports.prototype.BIRTHDAY = undefined;

  /**
   * @member {String} STATUS
   */
  exports.prototype.STATUS = undefined;

  /**
   * @member {String} CARD_TYPE
   */
  exports.prototype.CARD_TYPE = undefined;

  /**
   * @member {String} CARD_NO
   */
  exports.prototype.CARD_NO = undefined;

  /**
   * @member {String} IN_DATE
   */
  exports.prototype.IN_DATE = undefined;

  /**
   * @member {String} OUT_DATE
   */
  exports.prototype.OUT_DATE = undefined;

  /**
   * @member {String} FAN_NO
   */
  exports.prototype.FAN_NO = undefined;

  /**
   * @member {String} MOBILE_NO
   */
  exports.prototype.MOBILE_NO = undefined;

  /**
   * @member {String} DESCRIPTION
   */
  exports.prototype.DESCRIPTION = undefined;

  /**
   * @member {String} CREATE_TIME
   */
  exports.prototype.CREATE_TIME = undefined;

  /**
   * @member {String} UPDATE_TIME
   */
  exports.prototype.UPDATE_TIME = undefined;

  /**
   * @member {String} TENANT_ID
   */
  exports.prototype.TENANT_ID = undefined;

  /**
   * @member {String} PARTY
   */
  exports.prototype.PARTY = undefined;

  /**
   * @member {String} DEGREE
   */
  exports.prototype.DEGREE = undefined;

  /**
   * @member {String} REMARK
   */
  exports.prototype.REMARK = undefined;

  /**
   * @member {String} O_TEL
   */
  exports.prototype.O_TEL = undefined;

  /**
   * @member {String} O_ADDRESS
   */
  exports.prototype.O_ADDRESS = undefined;

  /**
   * @member {String} O_EMAIL
   */
  exports.prototype.O_EMAIL = undefined;

  /**
   * @member {String} H_TEL
   */
  exports.prototype.H_TEL = undefined;

  /**
   * @member {String} H_ADDRESS
   */
  exports.prototype.H_ADDRESS = undefined;

  /**
   * @member {String} H_ZIPCODE
   */
  exports.prototype.H_ZIPCODE = undefined;

  /**
   * @member {String} P_EMAIL
   */
  exports.prototype.P_EMAIL = undefined;

  /**
   * @member {String} QQ
   */
  exports.prototype.QQ = undefined;

  /**
   * @member {String} WEIBO
   */
  exports.prototype.WEIBO = undefined;

  /**
   * @member {String} WECHAT
   */
  exports.prototype.WECHAT = undefined;

  /**
   * @member {Number} IS_FIXED
   */
  exports.prototype.IS_FIXED = undefined;


  return exports;

}));
