/*
 * XgeneCloud
 * Create APIs at the speed of your thoughts
 *
 * OpenAPI spec version: 1.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.18
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.XgeneCloud) {
      root.XgeneCloud = {};
    }
    root.XgeneCloud.CofOperationLogDetail = factory(root.XgeneCloud.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';

  /**
   * The CofOperationLogDetail model module.
   * @module model/CofOperationLogDetail
   * @version 1.0.0
   */

  /**
   * Constructs a new <code>CofOperationLogDetail</code>.
   * @alias module:model/CofOperationLogDetail
   * @class
   */
  var exports = function() {
  };

  /**
   * Constructs a <code>CofOperationLogDetail</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/CofOperationLogDetail} obj Optional instance to populate.
   * @return {module:model/CofOperationLogDetail} The populated <code>CofOperationLogDetail</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();
      if (data.hasOwnProperty('ID'))
        obj.ID = ApiClient.convertToType(data['ID'], 'String');
      if (data.hasOwnProperty('OLD_DATA_JSON'))
        obj.OLD_DATA_JSON = ApiClient.convertToType(data['OLD_DATA_JSON'], 'String');
      if (data.hasOwnProperty('NEW_DATA_JSON'))
        obj.NEW_DATA_JSON = ApiClient.convertToType(data['NEW_DATA_JSON'], 'String');
    }
    return obj;
  }

  /**
   * @member {String} ID
   */
  exports.prototype.ID = undefined;

  /**
   * @member {String} OLD_DATA_JSON
   */
  exports.prototype.OLD_DATA_JSON = undefined;

  /**
   * @member {String} NEW_DATA_JSON
   */
  exports.prototype.NEW_DATA_JSON = undefined;


  return exports;

}));
