/*
 * XgeneCloud
 * Create APIs at the speed of your thoughts
 *
 * OpenAPI spec version: 1.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.18
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/CofPositionEmpMapping'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('../model/CofPositionEmpMapping'));
  } else {
    // Browser globals (root is window)
    if (!root.XgeneCloud) {
      root.XgeneCloud = {};
    }
    root.XgeneCloud.CofPositionEmpMappingApi = factory(root.XgeneCloud.ApiClient, root.XgeneCloud.CofPositionEmpMapping);
  }
}(this, function(ApiClient, CofPositionEmpMapping) {
  'use strict';

  /**
   * CofPositionEmpMapping service.
   * @module api/CofPositionEmpMappingApi
   * @version 1.0.0
   */

  /**
   * Constructs a new CofPositionEmpMappingApi. 
   * @alias module:api/CofPositionEmpMappingApi
   * @class
   * @param {module:ApiClient} [apiClient] Optional API client implementation to use,
   * default to {@link module:ApiClient#instance} if unspecified.
   */
  var exports = function(apiClient) {
    this.apiClient = apiClient || ApiClient.instance;


    /**
     * Callback function to receive the result of the addcofPositionEmpMapping operation.
     * @callback module:api/CofPositionEmpMappingApi~addcofPositionEmpMappingCallback
     * @param {String} error Error message, if any.
     * @param data This operation does not return a value.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Add a new cof_position_emp_mapping
     * 
     * @param {module:model/CofPositionEmpMapping} body cof_position_emp_mapping object that needs to add
     * @param {module:api/CofPositionEmpMappingApi~addcofPositionEmpMappingCallback} callback The callback function, accepting three arguments: error, data, response
     */
    this.addcofPositionEmpMapping = function(body, callback) {
      var postBody = body;

      // verify the required parameter 'body' is set
      if (body === undefined || body === null) {
        throw new Error("Missing the required parameter 'body' when calling addcofPositionEmpMapping");
      }


      var pathParams = {
      };
      var queryParams = {
      };
      var collectionQueryParams = {
      };
      var headerParams = {
      };
      var formParams = {
      };

      var authNames = [];
      var contentTypes = ['application/json'];
      var accepts = ['application/json'];
      var returnType = null;

      return this.apiClient.callApi(
        '/api/v1/cof_position_emp_mapping', 'POST',
        pathParams, queryParams, collectionQueryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }

    /**
     * Callback function to receive the result of the bulkcofPositionEmpMappingInsert operation.
     * @callback module:api/CofPositionEmpMappingApi~bulkcofPositionEmpMappingInsertCallback
     * @param {String} error Error message, if any.
     * @param data This operation does not return a value.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Bulk cof_position_emp_mapping insert
     * 
     * @param {Array.<module:model/CofPositionEmpMapping>} body cof_position_emp_mapping objects
     * @param {module:api/CofPositionEmpMappingApi~bulkcofPositionEmpMappingInsertCallback} callback The callback function, accepting three arguments: error, data, response
     */
    this.bulkcofPositionEmpMappingInsert = function(body, callback) {
      var postBody = body;

      // verify the required parameter 'body' is set
      if (body === undefined || body === null) {
        throw new Error("Missing the required parameter 'body' when calling bulkcofPositionEmpMappingInsert");
      }


      var pathParams = {
      };
      var queryParams = {
      };
      var collectionQueryParams = {
      };
      var headerParams = {
      };
      var formParams = {
      };

      var authNames = [];
      var contentTypes = ['application/json'];
      var accepts = ['application/json'];
      var returnType = null;

      return this.apiClient.callApi(
        '/api/v1/cof_position_emp_mapping/bulk', 'POST',
        pathParams, queryParams, collectionQueryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }

    /**
     * Callback function to receive the result of the checkcofPositionEmpMappingExists operation.
     * @callback module:api/CofPositionEmpMappingApi~checkcofPositionEmpMappingExistsCallback
     * @param {String} error Error message, if any.
     * @param {'Boolean'} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Check cof_position_emp_mapping with provided ID exists
     * Returns a single cof_position_emp_mapping
     * @param {Number} cofPositionEmpMappingId ID of cof_position_emp_mapping
     * @param {module:api/CofPositionEmpMappingApi~checkcofPositionEmpMappingExistsCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link 'Boolean'}
     */
    this.checkcofPositionEmpMappingExists = function(cofPositionEmpMappingId, callback) {
      var postBody = null;

      // verify the required parameter 'cofPositionEmpMappingId' is set
      if (cofPositionEmpMappingId === undefined || cofPositionEmpMappingId === null) {
        throw new Error("Missing the required parameter 'cofPositionEmpMappingId' when calling checkcofPositionEmpMappingExists");
      }


      var pathParams = {
        'cof_position_emp_mappingId': cofPositionEmpMappingId
      };
      var queryParams = {
      };
      var collectionQueryParams = {
      };
      var headerParams = {
      };
      var formParams = {
      };

      var authNames = [];
      var contentTypes = [];
      var accepts = ['application/json'];
      var returnType = 'Boolean';

      return this.apiClient.callApi(
        '/api/v1/cof_position_emp_mapping/{cof_position_emp_mappingId}/exists', 'GET',
        pathParams, queryParams, collectionQueryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }

    /**
     * Callback function to receive the result of the cofPositionEmpMappingAggregate operation.
     * @callback module:api/CofPositionEmpMappingApi~cofPositionEmpMappingAggregateCallback
     * @param {String} error Error message, if any.
     * @param {module:model/CofPositionEmpMapping} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Get first one from filtered data
     * 
     * @param {Object} columnName Column name
     * @param {Object} fields Column name
     * @param {Object} func Comma seperated aggregate functions
     * @param {Object} opts Optional parameters
     * @param {Object} opts.having Having expression
     * @param {Object} opts.fields2 Comma seperated fields from the model
     * @param {Number} opts.limit Page size limit
     * @param {Number} opts.offset Pagination offset
     * @param {String} opts.sort Comma seperated sort fields
     * @param {module:api/CofPositionEmpMappingApi~cofPositionEmpMappingAggregateCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/CofPositionEmpMapping}
     */
    this.cofPositionEmpMappingAggregate = function(columnName, fields, func, opts, callback) {
      opts = opts || {};
      var postBody = null;

      // verify the required parameter 'columnName' is set
      if (columnName === undefined || columnName === null) {
        throw new Error("Missing the required parameter 'columnName' when calling cofPositionEmpMappingAggregate");
      }

      // verify the required parameter 'fields' is set
      if (fields === undefined || fields === null) {
        throw new Error("Missing the required parameter 'fields' when calling cofPositionEmpMappingAggregate");
      }

      // verify the required parameter 'func' is set
      if (func === undefined || func === null) {
        throw new Error("Missing the required parameter 'func' when calling cofPositionEmpMappingAggregate");
      }


      var pathParams = {
        'columnName': columnName,
        'fields': fields,
        'func': func
      };
      var queryParams = {
        'having': opts['having'],
        'fields': opts['fields2'],
        'limit': opts['limit'],
        'offset': opts['offset'],
        'sort': opts['sort'],
      };
      var collectionQueryParams = {
      };
      var headerParams = {
      };
      var formParams = {
      };

      var authNames = [];
      var contentTypes = ['application/json'];
      var accepts = ['application/json'];
      var returnType = CofPositionEmpMapping;

      return this.apiClient.callApi(
        '/api/v1/cof_position_emp_mapping/aggregate/{columnName}', 'GET',
        pathParams, queryParams, collectionQueryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }

    /**
     * Callback function to receive the result of the cofPositionEmpMappingDistinct operation.
     * @callback module:api/CofPositionEmpMappingApi~cofPositionEmpMappingDistinctCallback
     * @param {String} error Error message, if any.
     * @param {Array.<Object>} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Get first one from filtered data
     * 
     * @param {Object} columnName Column name
     * @param {Object} opts Optional parameters
     * @param {Object} opts.where Where expression
     * @param {Number} opts.limit Page size limit
     * @param {Number} opts.offset Pagination offset
     * @param {String} opts.sort Comma seperated sort fieldst
     * @param {module:api/CofPositionEmpMappingApi~cofPositionEmpMappingDistinctCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link Array.<Object>}
     */
    this.cofPositionEmpMappingDistinct = function(columnName, opts, callback) {
      opts = opts || {};
      var postBody = null;

      // verify the required parameter 'columnName' is set
      if (columnName === undefined || columnName === null) {
        throw new Error("Missing the required parameter 'columnName' when calling cofPositionEmpMappingDistinct");
      }


      var pathParams = {
        'columnName': columnName
      };
      var queryParams = {
        'where': opts['where'],
        'limit': opts['limit'],
        'offset': opts['offset'],
        'sort': opts['sort'],
      };
      var collectionQueryParams = {
      };
      var headerParams = {
      };
      var formParams = {
      };

      var authNames = [];
      var contentTypes = ['application/json'];
      var accepts = ['application/json'];
      var returnType = [Object];

      return this.apiClient.callApi(
        '/api/v1/cof_position_emp_mapping/distinct/{columnName}', 'GET',
        pathParams, queryParams, collectionQueryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }

    /**
     * Callback function to receive the result of the cofPositionEmpMappingDistribution operation.
     * @callback module:api/CofPositionEmpMappingApi~cofPositionEmpMappingDistributionCallback
     * @param {String} error Error message, if any.
     * @param {Array.<Object>} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * 
     * 
     * @param {Object} columnName Column name
     * @param {Object} opts Optional parameters
     * @param {Number} opts.min min value
     * @param {Number} opts.max max value
     * @param {Number} opts.step step value
     * @param {Number} opts.steps steps value
     * @param {String} opts.func comma separated aggregation functions
     * @param {module:api/CofPositionEmpMappingApi~cofPositionEmpMappingDistributionCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link Array.<Object>}
     */
    this.cofPositionEmpMappingDistribution = function(columnName, opts, callback) {
      opts = opts || {};
      var postBody = null;

      // verify the required parameter 'columnName' is set
      if (columnName === undefined || columnName === null) {
        throw new Error("Missing the required parameter 'columnName' when calling cofPositionEmpMappingDistribution");
      }


      var pathParams = {
        'columnName': columnName
      };
      var queryParams = {
        'min': opts['min'],
        'max': opts['max'],
        'step': opts['step'],
        'steps': opts['steps'],
        'func': opts['func'],
      };
      var collectionQueryParams = {
      };
      var headerParams = {
      };
      var formParams = {
      };

      var authNames = [];
      var contentTypes = ['application/json'];
      var accepts = ['application/json'];
      var returnType = [Object];

      return this.apiClient.callApi(
        '/api/v1/cof_position_emp_mapping/distribution/{columnName}', 'GET',
        pathParams, queryParams, collectionQueryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }

    /**
     * Callback function to receive the result of the cofPositionEmpMappingGroupByColumn operation.
     * @callback module:api/CofPositionEmpMappingApi~cofPositionEmpMappingGroupByColumnCallback
     * @param {String} error Error message, if any.
     * @param {module:model/CofPositionEmpMapping} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Group by column
     * 
     * @param {Object} columnName Column name
     * @param {Object} opts Optional parameters
     * @param {Object} opts.where Where expression
     * @param {Number} opts.limit Page size limit
     * @param {Number} opts.offset Pagination offset
     * @param {String} opts.sort Comma seperated sort fieldst
     * @param {module:api/CofPositionEmpMappingApi~cofPositionEmpMappingGroupByColumnCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/CofPositionEmpMapping}
     */
    this.cofPositionEmpMappingGroupByColumn = function(columnName, opts, callback) {
      opts = opts || {};
      var postBody = null;

      // verify the required parameter 'columnName' is set
      if (columnName === undefined || columnName === null) {
        throw new Error("Missing the required parameter 'columnName' when calling cofPositionEmpMappingGroupByColumn");
      }


      var pathParams = {
        'columnName': columnName
      };
      var queryParams = {
        'where': opts['where'],
        'limit': opts['limit'],
        'offset': opts['offset'],
        'sort': opts['sort'],
      };
      var collectionQueryParams = {
      };
      var headerParams = {
      };
      var formParams = {
      };

      var authNames = [];
      var contentTypes = ['application/json'];
      var accepts = ['application/json'];
      var returnType = CofPositionEmpMapping;

      return this.apiClient.callApi(
        '/api/v1/cof_position_emp_mapping/groupby/{columnName}', 'GET',
        pathParams, queryParams, collectionQueryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }

    /**
     * Callback function to receive the result of the deletecofPositionEmpMapping operation.
     * @callback module:api/CofPositionEmpMappingApi~deletecofPositionEmpMappingCallback
     * @param {String} error Error message, if any.
     * @param data This operation does not return a value.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Deletes a cof_position_emp_mapping
     * 
     * @param {Number} cofPositionEmpMappingId ID of cof_position_emp_mapping to return
     * @param {module:api/CofPositionEmpMappingApi~deletecofPositionEmpMappingCallback} callback The callback function, accepting three arguments: error, data, response
     */
    this.deletecofPositionEmpMapping = function(cofPositionEmpMappingId, callback) {
      var postBody = null;

      // verify the required parameter 'cofPositionEmpMappingId' is set
      if (cofPositionEmpMappingId === undefined || cofPositionEmpMappingId === null) {
        throw new Error("Missing the required parameter 'cofPositionEmpMappingId' when calling deletecofPositionEmpMapping");
      }


      var pathParams = {
        'cof_position_emp_mappingId': cofPositionEmpMappingId
      };
      var queryParams = {
      };
      var collectionQueryParams = {
      };
      var headerParams = {
      };
      var formParams = {
      };

      var authNames = [];
      var contentTypes = [];
      var accepts = ['application/json'];
      var returnType = null;

      return this.apiClient.callApi(
        '/api/v1/cof_position_emp_mapping/{cof_position_emp_mappingId}', 'DELETE',
        pathParams, queryParams, collectionQueryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }

    /**
     * Callback function to receive the result of the deletecofPositionEmpMapping_0 operation.
     * @callback module:api/CofPositionEmpMappingApi~deletecofPositionEmpMapping_0Callback
     * @param {String} error Error message, if any.
     * @param data This operation does not return a value.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Deletes a cof_position_emp_mapping
     * 
     * @param {Array.<module:model/CofPositionEmpMapping>} body cof_position_emp_mapping objects contains id
     * @param {module:api/CofPositionEmpMappingApi~deletecofPositionEmpMapping_0Callback} callback The callback function, accepting three arguments: error, data, response
     */
    this.deletecofPositionEmpMapping_0 = function(body, callback) {
      var postBody = body;

      // verify the required parameter 'body' is set
      if (body === undefined || body === null) {
        throw new Error("Missing the required parameter 'body' when calling deletecofPositionEmpMapping_0");
      }


      var pathParams = {
      };
      var queryParams = {
      };
      var collectionQueryParams = {
      };
      var headerParams = {
      };
      var formParams = {
      };

      var authNames = [];
      var contentTypes = [];
      var accepts = ['application/json'];
      var returnType = null;

      return this.apiClient.callApi(
        '/api/v1/cof_position_emp_mapping/bulk', 'DELETE',
        pathParams, queryParams, collectionQueryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }

    /**
     * Callback function to receive the result of the findOnecofPositionEmpMapping operation.
     * @callback module:api/CofPositionEmpMappingApi~findOnecofPositionEmpMappingCallback
     * @param {String} error Error message, if any.
     * @param {module:model/CofPositionEmpMapping} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Get first one from filtered data
     * 
     * @param {Object} opts Optional parameters
     * @param {Object} opts.fields Comma seperated fields from the model
     * @param {Object} opts.where Where expression
     * @param {Number} opts.limit Page size limit
     * @param {Number} opts.offset Pagination offset
     * @param {String} opts.sort Comma seperated sort fieldst
     * @param {module:api/CofPositionEmpMappingApi~findOnecofPositionEmpMappingCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/CofPositionEmpMapping}
     */
    this.findOnecofPositionEmpMapping = function(opts, callback) {
      opts = opts || {};
      var postBody = null;


      var pathParams = {
      };
      var queryParams = {
        'fields': opts['fields'],
        'where': opts['where'],
        'limit': opts['limit'],
        'offset': opts['offset'],
        'sort': opts['sort'],
      };
      var collectionQueryParams = {
      };
      var headerParams = {
      };
      var formParams = {
      };

      var authNames = [];
      var contentTypes = ['application/json'];
      var accepts = ['application/json'];
      var returnType = CofPositionEmpMapping;

      return this.apiClient.callApi(
        '/api/v1/cof_position_emp_mapping/findOne', 'GET',
        pathParams, queryParams, collectionQueryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }

    /**
     * Callback function to receive the result of the getcofPositionEmpMapping operation.
     * @callback module:api/CofPositionEmpMappingApi~getcofPositionEmpMappingCallback
     * @param {String} error Error message, if any.
     * @param data This operation does not return a value.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Get list
     * 
     * @param {Object} opts Optional parameters
     * @param {Object} opts.fields Comma seperated fields from the model
     * @param {Object} opts.where Where expression
     * @param {Number} opts.limit Page size limit
     * @param {Number} opts.offset Pagination offset
     * @param {String} opts.sort Comma seperated sort fields
     * @param {module:api/CofPositionEmpMappingApi~getcofPositionEmpMappingCallback} callback The callback function, accepting three arguments: error, data, response
     */
    this.getcofPositionEmpMapping = function(opts, callback) {
      opts = opts || {};
      var postBody = null;


      var pathParams = {
      };
      var queryParams = {
        'fields': opts['fields'],
        'where': opts['where'],
        'limit': opts['limit'],
        'offset': opts['offset'],
        'sort': opts['sort'],
      };
      var collectionQueryParams = {
      };
      var headerParams = {
      };
      var formParams = {
      };

      var authNames = [];
      var contentTypes = ['application/json'];
      var accepts = ['application/json'];
      var returnType = null;

      return this.apiClient.callApi(
        '/api/v1/cof_position_emp_mapping', 'GET',
        pathParams, queryParams, collectionQueryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }

    /**
     * Callback function to receive the result of the getcofPositionEmpMappingById operation.
     * @callback module:api/CofPositionEmpMappingApi~getcofPositionEmpMappingByIdCallback
     * @param {String} error Error message, if any.
     * @param {module:model/CofPositionEmpMapping} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Find cof_position_emp_mapping by ID
     * Returns a single cof_position_emp_mapping
     * @param {Number} cofPositionEmpMappingId ID of cof_position_emp_mapping to return
     * @param {module:api/CofPositionEmpMappingApi~getcofPositionEmpMappingByIdCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/CofPositionEmpMapping}
     */
    this.getcofPositionEmpMappingById = function(cofPositionEmpMappingId, callback) {
      var postBody = null;

      // verify the required parameter 'cofPositionEmpMappingId' is set
      if (cofPositionEmpMappingId === undefined || cofPositionEmpMappingId === null) {
        throw new Error("Missing the required parameter 'cofPositionEmpMappingId' when calling getcofPositionEmpMappingById");
      }


      var pathParams = {
        'cof_position_emp_mappingId': cofPositionEmpMappingId
      };
      var queryParams = {
      };
      var collectionQueryParams = {
      };
      var headerParams = {
      };
      var formParams = {
      };

      var authNames = [];
      var contentTypes = [];
      var accepts = ['application/json'];
      var returnType = CofPositionEmpMapping;

      return this.apiClient.callApi(
        '/api/v1/cof_position_emp_mapping/{cof_position_emp_mappingId}', 'GET',
        pathParams, queryParams, collectionQueryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }

    /**
     * Callback function to receive the result of the getcofPositionEmpMappingCount operation.
     * @callback module:api/CofPositionEmpMappingApi~getcofPositionEmpMappingCountCallback
     * @param {String} error Error message, if any.
     * @param {Object} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Get cof_position_emp_mapping count
     * @param {Object} opts Optional parameters
     * @param {Object} opts.where Where expression
     * @param {module:api/CofPositionEmpMappingApi~getcofPositionEmpMappingCountCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link Object}
     */
    this.getcofPositionEmpMappingCount = function(opts, callback) {
      opts = opts || {};
      var postBody = null;


      var pathParams = {
      };
      var queryParams = {
        'where': opts['where'],
      };
      var collectionQueryParams = {
      };
      var headerParams = {
      };
      var formParams = {
      };

      var authNames = [];
      var contentTypes = ['application/json'];
      var accepts = ['application/json'];
      var returnType = Object;

      return this.apiClient.callApi(
        '/api/v1/cof_position_emp_mapping/count', 'GET',
        pathParams, queryParams, collectionQueryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }

    /**
     * Callback function to receive the result of the updatecofPositionEmpMapping operation.
     * @callback module:api/CofPositionEmpMappingApi~updatecofPositionEmpMappingCallback
     * @param {String} error Error message, if any.
     * @param data This operation does not return a value.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Updates a cof_position_emp_mapping
     * 
     * @param {Number} cofPositionEmpMappingId ID of cof_position_emp_mapping to return
     * @param {module:model/CofPositionEmpMapping} body cof_position_emp_mapping object that needs to be added to the store
     * @param {module:api/CofPositionEmpMappingApi~updatecofPositionEmpMappingCallback} callback The callback function, accepting three arguments: error, data, response
     */
    this.updatecofPositionEmpMapping = function(cofPositionEmpMappingId, body, callback) {
      var postBody = body;

      // verify the required parameter 'cofPositionEmpMappingId' is set
      if (cofPositionEmpMappingId === undefined || cofPositionEmpMappingId === null) {
        throw new Error("Missing the required parameter 'cofPositionEmpMappingId' when calling updatecofPositionEmpMapping");
      }

      // verify the required parameter 'body' is set
      if (body === undefined || body === null) {
        throw new Error("Missing the required parameter 'body' when calling updatecofPositionEmpMapping");
      }


      var pathParams = {
        'cof_position_emp_mappingId': cofPositionEmpMappingId
      };
      var queryParams = {
      };
      var collectionQueryParams = {
      };
      var headerParams = {
      };
      var formParams = {
      };

      var authNames = [];
      var contentTypes = ['application/json'];
      var accepts = ['application/json'];
      var returnType = null;

      return this.apiClient.callApi(
        '/api/v1/cof_position_emp_mapping/{cof_position_emp_mappingId}', 'PUT',
        pathParams, queryParams, collectionQueryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }

    /**
     * Callback function to receive the result of the updatecofPositionEmpMapping_0 operation.
     * @callback module:api/CofPositionEmpMappingApi~updatecofPositionEmpMapping_0Callback
     * @param {String} error Error message, if any.
     * @param data This operation does not return a value.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Updates a cof_position_emp_mapping
     * 
     * @param {Array.<module:model/CofPositionEmpMapping>} body cof_position_emp_mapping objects with id
     * @param {module:api/CofPositionEmpMappingApi~updatecofPositionEmpMapping_0Callback} callback The callback function, accepting three arguments: error, data, response
     */
    this.updatecofPositionEmpMapping_0 = function(body, callback) {
      var postBody = body;

      // verify the required parameter 'body' is set
      if (body === undefined || body === null) {
        throw new Error("Missing the required parameter 'body' when calling updatecofPositionEmpMapping_0");
      }


      var pathParams = {
      };
      var queryParams = {
      };
      var collectionQueryParams = {
      };
      var headerParams = {
      };
      var formParams = {
      };

      var authNames = [];
      var contentTypes = ['application/json'];
      var accepts = ['application/json'];
      var returnType = null;

      return this.apiClient.callApi(
        '/api/v1/cof_position_emp_mapping/bulk', 'PUT',
        pathParams, queryParams, collectionQueryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }
  };

  return exports;
}));
