/*
 * XgeneCloud
 * Create APIs at the speed of your thoughts
 *
 * OpenAPI spec version: 1.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.18
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/CofWorkgroupEmpMapping'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('../model/CofWorkgroupEmpMapping'));
  } else {
    // Browser globals (root is window)
    if (!root.XgeneCloud) {
      root.XgeneCloud = {};
    }
    root.XgeneCloud.CofWorkgroupEmpMappingApi = factory(root.XgeneCloud.ApiClient, root.XgeneCloud.CofWorkgroupEmpMapping);
  }
}(this, function(ApiClient, CofWorkgroupEmpMapping) {
  'use strict';

  /**
   * CofWorkgroupEmpMapping service.
   * @module api/CofWorkgroupEmpMappingApi
   * @version 1.0.0
   */

  /**
   * Constructs a new CofWorkgroupEmpMappingApi. 
   * @alias module:api/CofWorkgroupEmpMappingApi
   * @class
   * @param {module:ApiClient} [apiClient] Optional API client implementation to use,
   * default to {@link module:ApiClient#instance} if unspecified.
   */
  var exports = function(apiClient) {
    this.apiClient = apiClient || ApiClient.instance;


    /**
     * Callback function to receive the result of the addcofWorkgroupEmpMapping operation.
     * @callback module:api/CofWorkgroupEmpMappingApi~addcofWorkgroupEmpMappingCallback
     * @param {String} error Error message, if any.
     * @param data This operation does not return a value.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Add a new cof_workgroup_emp_mapping
     * 
     * @param {module:model/CofWorkgroupEmpMapping} body cof_workgroup_emp_mapping object that needs to add
     * @param {module:api/CofWorkgroupEmpMappingApi~addcofWorkgroupEmpMappingCallback} callback The callback function, accepting three arguments: error, data, response
     */
    this.addcofWorkgroupEmpMapping = function(body, callback) {
      var postBody = body;

      // verify the required parameter 'body' is set
      if (body === undefined || body === null) {
        throw new Error("Missing the required parameter 'body' when calling addcofWorkgroupEmpMapping");
      }


      var pathParams = {
      };
      var queryParams = {
      };
      var collectionQueryParams = {
      };
      var headerParams = {
      };
      var formParams = {
      };

      var authNames = [];
      var contentTypes = ['application/json'];
      var accepts = ['application/json'];
      var returnType = null;

      return this.apiClient.callApi(
        '/api/v1/cof_workgroup_emp_mapping', 'POST',
        pathParams, queryParams, collectionQueryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }

    /**
     * Callback function to receive the result of the bulkcofWorkgroupEmpMappingInsert operation.
     * @callback module:api/CofWorkgroupEmpMappingApi~bulkcofWorkgroupEmpMappingInsertCallback
     * @param {String} error Error message, if any.
     * @param data This operation does not return a value.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Bulk cof_workgroup_emp_mapping insert
     * 
     * @param {Array.<module:model/CofWorkgroupEmpMapping>} body cof_workgroup_emp_mapping objects
     * @param {module:api/CofWorkgroupEmpMappingApi~bulkcofWorkgroupEmpMappingInsertCallback} callback The callback function, accepting three arguments: error, data, response
     */
    this.bulkcofWorkgroupEmpMappingInsert = function(body, callback) {
      var postBody = body;

      // verify the required parameter 'body' is set
      if (body === undefined || body === null) {
        throw new Error("Missing the required parameter 'body' when calling bulkcofWorkgroupEmpMappingInsert");
      }


      var pathParams = {
      };
      var queryParams = {
      };
      var collectionQueryParams = {
      };
      var headerParams = {
      };
      var formParams = {
      };

      var authNames = [];
      var contentTypes = ['application/json'];
      var accepts = ['application/json'];
      var returnType = null;

      return this.apiClient.callApi(
        '/api/v1/cof_workgroup_emp_mapping/bulk', 'POST',
        pathParams, queryParams, collectionQueryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }

    /**
     * Callback function to receive the result of the checkcofWorkgroupEmpMappingExists operation.
     * @callback module:api/CofWorkgroupEmpMappingApi~checkcofWorkgroupEmpMappingExistsCallback
     * @param {String} error Error message, if any.
     * @param {'Boolean'} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Check cof_workgroup_emp_mapping with provided ID exists
     * Returns a single cof_workgroup_emp_mapping
     * @param {Number} cofWorkgroupEmpMappingId ID of cof_workgroup_emp_mapping
     * @param {module:api/CofWorkgroupEmpMappingApi~checkcofWorkgroupEmpMappingExistsCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link 'Boolean'}
     */
    this.checkcofWorkgroupEmpMappingExists = function(cofWorkgroupEmpMappingId, callback) {
      var postBody = null;

      // verify the required parameter 'cofWorkgroupEmpMappingId' is set
      if (cofWorkgroupEmpMappingId === undefined || cofWorkgroupEmpMappingId === null) {
        throw new Error("Missing the required parameter 'cofWorkgroupEmpMappingId' when calling checkcofWorkgroupEmpMappingExists");
      }


      var pathParams = {
        'cof_workgroup_emp_mappingId': cofWorkgroupEmpMappingId
      };
      var queryParams = {
      };
      var collectionQueryParams = {
      };
      var headerParams = {
      };
      var formParams = {
      };

      var authNames = [];
      var contentTypes = [];
      var accepts = ['application/json'];
      var returnType = 'Boolean';

      return this.apiClient.callApi(
        '/api/v1/cof_workgroup_emp_mapping/{cof_workgroup_emp_mappingId}/exists', 'GET',
        pathParams, queryParams, collectionQueryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }

    /**
     * Callback function to receive the result of the cofWorkgroupEmpMappingAggregate operation.
     * @callback module:api/CofWorkgroupEmpMappingApi~cofWorkgroupEmpMappingAggregateCallback
     * @param {String} error Error message, if any.
     * @param {module:model/CofWorkgroupEmpMapping} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Get first one from filtered data
     * 
     * @param {Object} columnName Column name
     * @param {Object} fields Column name
     * @param {Object} func Comma seperated aggregate functions
     * @param {Object} opts Optional parameters
     * @param {Object} opts.having Having expression
     * @param {Object} opts.fields2 Comma seperated fields from the model
     * @param {Number} opts.limit Page size limit
     * @param {Number} opts.offset Pagination offset
     * @param {String} opts.sort Comma seperated sort fields
     * @param {module:api/CofWorkgroupEmpMappingApi~cofWorkgroupEmpMappingAggregateCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/CofWorkgroupEmpMapping}
     */
    this.cofWorkgroupEmpMappingAggregate = function(columnName, fields, func, opts, callback) {
      opts = opts || {};
      var postBody = null;

      // verify the required parameter 'columnName' is set
      if (columnName === undefined || columnName === null) {
        throw new Error("Missing the required parameter 'columnName' when calling cofWorkgroupEmpMappingAggregate");
      }

      // verify the required parameter 'fields' is set
      if (fields === undefined || fields === null) {
        throw new Error("Missing the required parameter 'fields' when calling cofWorkgroupEmpMappingAggregate");
      }

      // verify the required parameter 'func' is set
      if (func === undefined || func === null) {
        throw new Error("Missing the required parameter 'func' when calling cofWorkgroupEmpMappingAggregate");
      }


      var pathParams = {
        'columnName': columnName,
        'fields': fields,
        'func': func
      };
      var queryParams = {
        'having': opts['having'],
        'fields': opts['fields2'],
        'limit': opts['limit'],
        'offset': opts['offset'],
        'sort': opts['sort'],
      };
      var collectionQueryParams = {
      };
      var headerParams = {
      };
      var formParams = {
      };

      var authNames = [];
      var contentTypes = ['application/json'];
      var accepts = ['application/json'];
      var returnType = CofWorkgroupEmpMapping;

      return this.apiClient.callApi(
        '/api/v1/cof_workgroup_emp_mapping/aggregate/{columnName}', 'GET',
        pathParams, queryParams, collectionQueryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }

    /**
     * Callback function to receive the result of the cofWorkgroupEmpMappingDistinct operation.
     * @callback module:api/CofWorkgroupEmpMappingApi~cofWorkgroupEmpMappingDistinctCallback
     * @param {String} error Error message, if any.
     * @param {Array.<Object>} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Get first one from filtered data
     * 
     * @param {Object} columnName Column name
     * @param {Object} opts Optional parameters
     * @param {Object} opts.where Where expression
     * @param {Number} opts.limit Page size limit
     * @param {Number} opts.offset Pagination offset
     * @param {String} opts.sort Comma seperated sort fieldst
     * @param {module:api/CofWorkgroupEmpMappingApi~cofWorkgroupEmpMappingDistinctCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link Array.<Object>}
     */
    this.cofWorkgroupEmpMappingDistinct = function(columnName, opts, callback) {
      opts = opts || {};
      var postBody = null;

      // verify the required parameter 'columnName' is set
      if (columnName === undefined || columnName === null) {
        throw new Error("Missing the required parameter 'columnName' when calling cofWorkgroupEmpMappingDistinct");
      }


      var pathParams = {
        'columnName': columnName
      };
      var queryParams = {
        'where': opts['where'],
        'limit': opts['limit'],
        'offset': opts['offset'],
        'sort': opts['sort'],
      };
      var collectionQueryParams = {
      };
      var headerParams = {
      };
      var formParams = {
      };

      var authNames = [];
      var contentTypes = ['application/json'];
      var accepts = ['application/json'];
      var returnType = [Object];

      return this.apiClient.callApi(
        '/api/v1/cof_workgroup_emp_mapping/distinct/{columnName}', 'GET',
        pathParams, queryParams, collectionQueryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }

    /**
     * Callback function to receive the result of the cofWorkgroupEmpMappingDistribution operation.
     * @callback module:api/CofWorkgroupEmpMappingApi~cofWorkgroupEmpMappingDistributionCallback
     * @param {String} error Error message, if any.
     * @param {Array.<Object>} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * 
     * 
     * @param {Object} columnName Column name
     * @param {Object} opts Optional parameters
     * @param {Number} opts.min min value
     * @param {Number} opts.max max value
     * @param {Number} opts.step step value
     * @param {Number} opts.steps steps value
     * @param {String} opts.func comma separated aggregation functions
     * @param {module:api/CofWorkgroupEmpMappingApi~cofWorkgroupEmpMappingDistributionCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link Array.<Object>}
     */
    this.cofWorkgroupEmpMappingDistribution = function(columnName, opts, callback) {
      opts = opts || {};
      var postBody = null;

      // verify the required parameter 'columnName' is set
      if (columnName === undefined || columnName === null) {
        throw new Error("Missing the required parameter 'columnName' when calling cofWorkgroupEmpMappingDistribution");
      }


      var pathParams = {
        'columnName': columnName
      };
      var queryParams = {
        'min': opts['min'],
        'max': opts['max'],
        'step': opts['step'],
        'steps': opts['steps'],
        'func': opts['func'],
      };
      var collectionQueryParams = {
      };
      var headerParams = {
      };
      var formParams = {
      };

      var authNames = [];
      var contentTypes = ['application/json'];
      var accepts = ['application/json'];
      var returnType = [Object];

      return this.apiClient.callApi(
        '/api/v1/cof_workgroup_emp_mapping/distribution/{columnName}', 'GET',
        pathParams, queryParams, collectionQueryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }

    /**
     * Callback function to receive the result of the cofWorkgroupEmpMappingGroupByColumn operation.
     * @callback module:api/CofWorkgroupEmpMappingApi~cofWorkgroupEmpMappingGroupByColumnCallback
     * @param {String} error Error message, if any.
     * @param {module:model/CofWorkgroupEmpMapping} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Group by column
     * 
     * @param {Object} columnName Column name
     * @param {Object} opts Optional parameters
     * @param {Object} opts.where Where expression
     * @param {Number} opts.limit Page size limit
     * @param {Number} opts.offset Pagination offset
     * @param {String} opts.sort Comma seperated sort fieldst
     * @param {module:api/CofWorkgroupEmpMappingApi~cofWorkgroupEmpMappingGroupByColumnCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/CofWorkgroupEmpMapping}
     */
    this.cofWorkgroupEmpMappingGroupByColumn = function(columnName, opts, callback) {
      opts = opts || {};
      var postBody = null;

      // verify the required parameter 'columnName' is set
      if (columnName === undefined || columnName === null) {
        throw new Error("Missing the required parameter 'columnName' when calling cofWorkgroupEmpMappingGroupByColumn");
      }


      var pathParams = {
        'columnName': columnName
      };
      var queryParams = {
        'where': opts['where'],
        'limit': opts['limit'],
        'offset': opts['offset'],
        'sort': opts['sort'],
      };
      var collectionQueryParams = {
      };
      var headerParams = {
      };
      var formParams = {
      };

      var authNames = [];
      var contentTypes = ['application/json'];
      var accepts = ['application/json'];
      var returnType = CofWorkgroupEmpMapping;

      return this.apiClient.callApi(
        '/api/v1/cof_workgroup_emp_mapping/groupby/{columnName}', 'GET',
        pathParams, queryParams, collectionQueryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }

    /**
     * Callback function to receive the result of the deletecofWorkgroupEmpMapping operation.
     * @callback module:api/CofWorkgroupEmpMappingApi~deletecofWorkgroupEmpMappingCallback
     * @param {String} error Error message, if any.
     * @param data This operation does not return a value.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Deletes a cof_workgroup_emp_mapping
     * 
     * @param {Number} cofWorkgroupEmpMappingId ID of cof_workgroup_emp_mapping to return
     * @param {module:api/CofWorkgroupEmpMappingApi~deletecofWorkgroupEmpMappingCallback} callback The callback function, accepting three arguments: error, data, response
     */
    this.deletecofWorkgroupEmpMapping = function(cofWorkgroupEmpMappingId, callback) {
      var postBody = null;

      // verify the required parameter 'cofWorkgroupEmpMappingId' is set
      if (cofWorkgroupEmpMappingId === undefined || cofWorkgroupEmpMappingId === null) {
        throw new Error("Missing the required parameter 'cofWorkgroupEmpMappingId' when calling deletecofWorkgroupEmpMapping");
      }


      var pathParams = {
        'cof_workgroup_emp_mappingId': cofWorkgroupEmpMappingId
      };
      var queryParams = {
      };
      var collectionQueryParams = {
      };
      var headerParams = {
      };
      var formParams = {
      };

      var authNames = [];
      var contentTypes = [];
      var accepts = ['application/json'];
      var returnType = null;

      return this.apiClient.callApi(
        '/api/v1/cof_workgroup_emp_mapping/{cof_workgroup_emp_mappingId}', 'DELETE',
        pathParams, queryParams, collectionQueryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }

    /**
     * Callback function to receive the result of the deletecofWorkgroupEmpMapping_0 operation.
     * @callback module:api/CofWorkgroupEmpMappingApi~deletecofWorkgroupEmpMapping_0Callback
     * @param {String} error Error message, if any.
     * @param data This operation does not return a value.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Deletes a cof_workgroup_emp_mapping
     * 
     * @param {Array.<module:model/CofWorkgroupEmpMapping>} body cof_workgroup_emp_mapping objects contains id
     * @param {module:api/CofWorkgroupEmpMappingApi~deletecofWorkgroupEmpMapping_0Callback} callback The callback function, accepting three arguments: error, data, response
     */
    this.deletecofWorkgroupEmpMapping_0 = function(body, callback) {
      var postBody = body;

      // verify the required parameter 'body' is set
      if (body === undefined || body === null) {
        throw new Error("Missing the required parameter 'body' when calling deletecofWorkgroupEmpMapping_0");
      }


      var pathParams = {
      };
      var queryParams = {
      };
      var collectionQueryParams = {
      };
      var headerParams = {
      };
      var formParams = {
      };

      var authNames = [];
      var contentTypes = [];
      var accepts = ['application/json'];
      var returnType = null;

      return this.apiClient.callApi(
        '/api/v1/cof_workgroup_emp_mapping/bulk', 'DELETE',
        pathParams, queryParams, collectionQueryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }

    /**
     * Callback function to receive the result of the findOnecofWorkgroupEmpMapping operation.
     * @callback module:api/CofWorkgroupEmpMappingApi~findOnecofWorkgroupEmpMappingCallback
     * @param {String} error Error message, if any.
     * @param {module:model/CofWorkgroupEmpMapping} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Get first one from filtered data
     * 
     * @param {Object} opts Optional parameters
     * @param {Object} opts.fields Comma seperated fields from the model
     * @param {Object} opts.where Where expression
     * @param {Number} opts.limit Page size limit
     * @param {Number} opts.offset Pagination offset
     * @param {String} opts.sort Comma seperated sort fieldst
     * @param {module:api/CofWorkgroupEmpMappingApi~findOnecofWorkgroupEmpMappingCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/CofWorkgroupEmpMapping}
     */
    this.findOnecofWorkgroupEmpMapping = function(opts, callback) {
      opts = opts || {};
      var postBody = null;


      var pathParams = {
      };
      var queryParams = {
        'fields': opts['fields'],
        'where': opts['where'],
        'limit': opts['limit'],
        'offset': opts['offset'],
        'sort': opts['sort'],
      };
      var collectionQueryParams = {
      };
      var headerParams = {
      };
      var formParams = {
      };

      var authNames = [];
      var contentTypes = ['application/json'];
      var accepts = ['application/json'];
      var returnType = CofWorkgroupEmpMapping;

      return this.apiClient.callApi(
        '/api/v1/cof_workgroup_emp_mapping/findOne', 'GET',
        pathParams, queryParams, collectionQueryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }

    /**
     * Callback function to receive the result of the getcofWorkgroupEmpMapping operation.
     * @callback module:api/CofWorkgroupEmpMappingApi~getcofWorkgroupEmpMappingCallback
     * @param {String} error Error message, if any.
     * @param data This operation does not return a value.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Get list
     * 
     * @param {Object} opts Optional parameters
     * @param {Object} opts.fields Comma seperated fields from the model
     * @param {Object} opts.where Where expression
     * @param {Number} opts.limit Page size limit
     * @param {Number} opts.offset Pagination offset
     * @param {String} opts.sort Comma seperated sort fields
     * @param {module:api/CofWorkgroupEmpMappingApi~getcofWorkgroupEmpMappingCallback} callback The callback function, accepting three arguments: error, data, response
     */
    this.getcofWorkgroupEmpMapping = function(opts, callback) {
      opts = opts || {};
      var postBody = null;


      var pathParams = {
      };
      var queryParams = {
        'fields': opts['fields'],
        'where': opts['where'],
        'limit': opts['limit'],
        'offset': opts['offset'],
        'sort': opts['sort'],
      };
      var collectionQueryParams = {
      };
      var headerParams = {
      };
      var formParams = {
      };

      var authNames = [];
      var contentTypes = ['application/json'];
      var accepts = ['application/json'];
      var returnType = null;

      return this.apiClient.callApi(
        '/api/v1/cof_workgroup_emp_mapping', 'GET',
        pathParams, queryParams, collectionQueryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }

    /**
     * Callback function to receive the result of the getcofWorkgroupEmpMappingById operation.
     * @callback module:api/CofWorkgroupEmpMappingApi~getcofWorkgroupEmpMappingByIdCallback
     * @param {String} error Error message, if any.
     * @param {module:model/CofWorkgroupEmpMapping} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Find cof_workgroup_emp_mapping by ID
     * Returns a single cof_workgroup_emp_mapping
     * @param {Number} cofWorkgroupEmpMappingId ID of cof_workgroup_emp_mapping to return
     * @param {module:api/CofWorkgroupEmpMappingApi~getcofWorkgroupEmpMappingByIdCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/CofWorkgroupEmpMapping}
     */
    this.getcofWorkgroupEmpMappingById = function(cofWorkgroupEmpMappingId, callback) {
      var postBody = null;

      // verify the required parameter 'cofWorkgroupEmpMappingId' is set
      if (cofWorkgroupEmpMappingId === undefined || cofWorkgroupEmpMappingId === null) {
        throw new Error("Missing the required parameter 'cofWorkgroupEmpMappingId' when calling getcofWorkgroupEmpMappingById");
      }


      var pathParams = {
        'cof_workgroup_emp_mappingId': cofWorkgroupEmpMappingId
      };
      var queryParams = {
      };
      var collectionQueryParams = {
      };
      var headerParams = {
      };
      var formParams = {
      };

      var authNames = [];
      var contentTypes = [];
      var accepts = ['application/json'];
      var returnType = CofWorkgroupEmpMapping;

      return this.apiClient.callApi(
        '/api/v1/cof_workgroup_emp_mapping/{cof_workgroup_emp_mappingId}', 'GET',
        pathParams, queryParams, collectionQueryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }

    /**
     * Callback function to receive the result of the getcofWorkgroupEmpMappingCount operation.
     * @callback module:api/CofWorkgroupEmpMappingApi~getcofWorkgroupEmpMappingCountCallback
     * @param {String} error Error message, if any.
     * @param {Object} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Get cof_workgroup_emp_mapping count
     * @param {Object} opts Optional parameters
     * @param {Object} opts.where Where expression
     * @param {module:api/CofWorkgroupEmpMappingApi~getcofWorkgroupEmpMappingCountCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link Object}
     */
    this.getcofWorkgroupEmpMappingCount = function(opts, callback) {
      opts = opts || {};
      var postBody = null;


      var pathParams = {
      };
      var queryParams = {
        'where': opts['where'],
      };
      var collectionQueryParams = {
      };
      var headerParams = {
      };
      var formParams = {
      };

      var authNames = [];
      var contentTypes = ['application/json'];
      var accepts = ['application/json'];
      var returnType = Object;

      return this.apiClient.callApi(
        '/api/v1/cof_workgroup_emp_mapping/count', 'GET',
        pathParams, queryParams, collectionQueryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }

    /**
     * Callback function to receive the result of the updatecofWorkgroupEmpMapping operation.
     * @callback module:api/CofWorkgroupEmpMappingApi~updatecofWorkgroupEmpMappingCallback
     * @param {String} error Error message, if any.
     * @param data This operation does not return a value.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Updates a cof_workgroup_emp_mapping
     * 
     * @param {Number} cofWorkgroupEmpMappingId ID of cof_workgroup_emp_mapping to return
     * @param {module:model/CofWorkgroupEmpMapping} body cof_workgroup_emp_mapping object that needs to be added to the store
     * @param {module:api/CofWorkgroupEmpMappingApi~updatecofWorkgroupEmpMappingCallback} callback The callback function, accepting three arguments: error, data, response
     */
    this.updatecofWorkgroupEmpMapping = function(cofWorkgroupEmpMappingId, body, callback) {
      var postBody = body;

      // verify the required parameter 'cofWorkgroupEmpMappingId' is set
      if (cofWorkgroupEmpMappingId === undefined || cofWorkgroupEmpMappingId === null) {
        throw new Error("Missing the required parameter 'cofWorkgroupEmpMappingId' when calling updatecofWorkgroupEmpMapping");
      }

      // verify the required parameter 'body' is set
      if (body === undefined || body === null) {
        throw new Error("Missing the required parameter 'body' when calling updatecofWorkgroupEmpMapping");
      }


      var pathParams = {
        'cof_workgroup_emp_mappingId': cofWorkgroupEmpMappingId
      };
      var queryParams = {
      };
      var collectionQueryParams = {
      };
      var headerParams = {
      };
      var formParams = {
      };

      var authNames = [];
      var contentTypes = ['application/json'];
      var accepts = ['application/json'];
      var returnType = null;

      return this.apiClient.callApi(
        '/api/v1/cof_workgroup_emp_mapping/{cof_workgroup_emp_mappingId}', 'PUT',
        pathParams, queryParams, collectionQueryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }

    /**
     * Callback function to receive the result of the updatecofWorkgroupEmpMapping_0 operation.
     * @callback module:api/CofWorkgroupEmpMappingApi~updatecofWorkgroupEmpMapping_0Callback
     * @param {String} error Error message, if any.
     * @param data This operation does not return a value.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Updates a cof_workgroup_emp_mapping
     * 
     * @param {Array.<module:model/CofWorkgroupEmpMapping>} body cof_workgroup_emp_mapping objects with id
     * @param {module:api/CofWorkgroupEmpMappingApi~updatecofWorkgroupEmpMapping_0Callback} callback The callback function, accepting three arguments: error, data, response
     */
    this.updatecofWorkgroupEmpMapping_0 = function(body, callback) {
      var postBody = body;

      // verify the required parameter 'body' is set
      if (body === undefined || body === null) {
        throw new Error("Missing the required parameter 'body' when calling updatecofWorkgroupEmpMapping_0");
      }


      var pathParams = {
      };
      var queryParams = {
      };
      var collectionQueryParams = {
      };
      var headerParams = {
      };
      var formParams = {
      };

      var authNames = [];
      var contentTypes = ['application/json'];
      var accepts = ['application/json'];
      var returnType = null;

      return this.apiClient.callApi(
        '/api/v1/cof_workgroup_emp_mapping/bulk', 'PUT',
        pathParams, queryParams, collectionQueryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }
  };

  return exports;
}));
