/*
 * XgeneCloud
 * Create APIs at the speed of your thoughts
 *
 * OpenAPI spec version: 1.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.18
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.XgeneCloud);
  }
}(this, function(expect, XgeneCloud) {
  'use strict';

  var instance;

  describe('(package)', function() {
    describe('Body2', function() {
      beforeEach(function() {
        instance = new XgeneCloud.Body2();
      });

      it('should create an instance of Body2', function() {
        // TODO: update the code to test Body2
        expect(instance).to.be.a(XgeneCloud.Body2);
      });

      it('should have the property currentPassword (base name: "currentPassword")', function() {
        // TODO: update the code to test the property currentPassword
        expect(instance).to.have.property('currentPassword');
        // expect(instance.currentPassword).to.be(expectedValueLiteral);
      });

      it('should have the property newPassword (base name: "newPassword")', function() {
        // TODO: update the code to test the property newPassword
        expect(instance).to.have.property('newPassword');
        // expect(instance.newPassword).to.be(expectedValueLiteral);
      });

    });
  });

}));
