/*
 * XgeneCloud
 * Create APIs at the speed of your thoughts
 *
 * OpenAPI spec version: 1.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.18
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.XgeneCloud);
  }
}(this, function(expect, XgeneCloud) {
  'use strict';

  var instance;

  describe('(package)', function() {
    describe('CofAuthRes', function() {
      beforeEach(function() {
        instance = new XgeneCloud.CofAuthRes();
      });

      it('should create an instance of CofAuthRes', function() {
        // TODO: update the code to test CofAuthRes
        expect(instance).to.be.a(XgeneCloud.CofAuthRes);
      });

      it('should have the property ID (base name: "ID")', function() {
        // TODO: update the code to test the property ID
        expect(instance).to.have.property('ID');
        // expect(instance.ID).to.be(expectedValueLiteral);
      });

      it('should have the property TYPE (base name: "TYPE")', function() {
        // TODO: update the code to test the property TYPE
        expect(instance).to.have.property('TYPE');
        // expect(instance.TYPE).to.be(expectedValueLiteral);
      });

      it('should have the property AUTH_TYPE (base name: "AUTH_TYPE")', function() {
        // TODO: update the code to test the property AUTH_TYPE
        expect(instance).to.have.property('AUTH_TYPE');
        // expect(instance.AUTH_TYPE).to.be(expectedValueLiteral);
      });

      it('should have the property AUTH_ID (base name: "AUTH_ID")', function() {
        // TODO: update the code to test the property AUTH_ID
        expect(instance).to.have.property('AUTH_ID');
        // expect(instance.AUTH_ID).to.be(expectedValueLiteral);
      });

      it('should have the property RES_TYPE (base name: "RES_TYPE")', function() {
        // TODO: update the code to test the property RES_TYPE
        expect(instance).to.have.property('RES_TYPE');
        // expect(instance.RES_TYPE).to.be(expectedValueLiteral);
      });

      it('should have the property RES_ID (base name: "RES_ID")', function() {
        // TODO: update the code to test the property RES_ID
        expect(instance).to.have.property('RES_ID');
        // expect(instance.RES_ID).to.be(expectedValueLiteral);
      });

      it('should have the property IS_FIXED (base name: "IS_FIXED")', function() {
        // TODO: update the code to test the property IS_FIXED
        expect(instance).to.have.property('IS_FIXED');
        // expect(instance.IS_FIXED).to.be(expectedValueLiteral);
      });

    });
  });

}));
